[project]
name = "project-zeus-market-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster>=1.12.14",
    "dagster-webserver>=1.12.14",
]
